import { useCallback, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { adminService } from './adminService.js';
import { useAdminData } from './useAdminData.js';
import { LoadState, Pagination } from './AdminCommon.jsx';
import { adminError, date, money, orderLabels, paymentLabels } from './adminModel.js';
import { ticketStatusLabel } from '../tickets/utils/digitalTickets.js';
export function AdminOrders({ tickets = false }) {
  const [page,setPage] = useState(0); const [search,setSearch] = useState(''); const [draft,setDraft] = useState(''); const [status,setStatus] = useState(''); const [payment,setPayment] = useState('');
  const state = useAdminData(useCallback(() => adminService.list(tickets ? 'tickets' : 'orders',{ page,search,status,payment }),[tickets,page,search,status,payment]));
  return <><h2>{tickets ? 'Tra cứu vé' : 'Đơn hàng'}</h2><form className="admin-filters" onSubmit={e => { e.preventDefault(); setSearch(draft); setPage(0); }}><input aria-label="Tìm kiếm" placeholder={tickets ? 'Mã vé' : 'Mã đơn, tên, email, số điện thoại'} value={draft} maxLength={120} onChange={e => setDraft(e.target.value)} /><button>Tìm kiếm</button>{!tickets && <><select aria-label="Trạng thái đơn" value={status} onChange={e => { setStatus(e.target.value); setPage(0); }}><option value="">Mọi trạng thái đơn</option>{Object.entries(orderLabels).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select><select aria-label="Thanh toán" value={payment} onChange={e => { setPayment(e.target.value); setPage(0); }}><option value="">Mọi trạng thái thanh toán</option>{Object.entries(paymentLabels).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></>}</form><LoadState state={state} retry={state.retry} />{state.data && <><div className="admin-table-wrap"><table><thead><tr>{(tickets ? ['Mã vé','Hạng vé / Đơn hàng','Trạng thái','Phát hành','Đã sử dụng'] : ['Mã đơn','Khách hàng','Email / Điện thoại','Số vé','Tổng tiền','Trạng thái đơn','Thanh toán','Ngày tạo']).map(l => <th key={l}>{l}</th>)}</tr></thead><tbody>{state.data.rows.map(r => <tr key={r.id}>{tickets ? <><td>{r.ticket_code}</td><td>{r.ticket_name}<br /><Link to={'/admin/orders/' + r.order?.order_code}>{r.order?.order_code}</Link></td><td>{ticketStatusLabel(r.status)}</td><td>{date(r.issued_at)}</td><td>{date(r.used_at)}</td></> : <><td><Link to={'/admin/orders/' + r.order_code}>{r.order_code}</Link></td><td>{r.customer_name}</td><td>{r.customer_email}<br />{r.customer_phone}</td><td>{r.total_quantity}</td><td>{money(r.total_amount)}</td><td>{orderLabels[r.status]}</td><td>{paymentLabels[r.payment_status]}</td><td>{date(r.created_at)}</td></>}</tr>)}</tbody></table></div>{!state.data.rows.length && <p>Không có kết quả phù hợp.</p>}<Pagination page={page} count={state.data.count} onChange={setPage} /></>}</>;
}
export function AdminOrderDetail() {
  const { orderCode } = useParams(); const [busy,setBusy] = useState(false); const [message,setMessage] = useState('');
  const state = useAdminData(useCallback(async () => { const order = await adminService.order(orderCode); return order ? { ...order,issued:await adminService.ticketCount(order.id) } : null; },[orderCode]));
  async function action(name) {
    if (!window.confirm(name === 'admin_confirm_order' ? 'Xác nhận đã nhận đủ tiền qua quy trình thủ công/ngoại tuyến? Vé điện tử sẽ được phát hành.' : 'Hủy đơn và thu hồi vé chưa sử dụng? Tồn kho sẽ được hoàn lại. Thao tác này không hoàn tiền.')) return;
    setBusy(true); setMessage(''); try { await adminService.rpc(name,{ p_order_id:state.data.id }); setMessage('Thao tác thành công.'); state.retry(); } catch (error) { setMessage(adminError(error)); } finally { setBusy(false); }
  }
  const o = state.data;
  return <><Link to="/admin/orders">← Đơn hàng</Link><h2>Chi tiết đơn hàng</h2><LoadState state={state} retry={state.retry} />{message && <p role="status">{message}</p>}{!state.loading && !state.error && !o && <p>Không tìm thấy đơn hàng.</p>}{o && <><div className="admin-card"><h3>{o.order_code}</h3><p>{o.customer_name} · {o.customer_email} · {o.customer_phone}</p><p>{orderLabels[o.status]} · {paymentLabels[o.payment_status]} · {date(o.created_at)}</p><p>{o.total_quantity} vé · Đã phát hành: {o.issued}</p><p>{o.inventory_released_at ? 'Đã hoàn tồn kho: ' + date(o.inventory_released_at) : 'Chưa ghi nhận hoàn tồn kho.'}</p></div><div className="admin-table-wrap"><table><thead><tr><th>Hạng vé</th><th>Số lượng</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>{o.order_items.map(i => <tr key={i.id}><td>{i.ticket_name}</td><td>{i.quantity}</td><td>{money(i.unit_price)}</td><td>{money(i.subtotal)}</td></tr>)}</tbody></table></div><p className="admin-total">Tổng cộng: {money(o.total_amount)}</p><p className="admin-note">Xác nhận thanh toán thủ công dành cho phát triển và giao dịch ngoại tuyến. Hủy đơn không thực hiện hoàn tiền.</p><div className="admin-actions">{o.status === 'pending' && ['unpaid','failed'].includes(o.payment_status) && <button className="button button-pink" disabled={busy} onClick={() => action('admin_confirm_order')}>XÁC NHẬN ĐÃ THANH TOÁN</button>}{o.status !== 'cancelled' && o.payment_status !== 'refunded' && <button disabled={busy} onClick={() => action('admin_cancel_order')}>Hủy đơn hàng</button>}{busy && <span role="status">Đang xử lý...</span>}</div></>}</>;
}
